atpproject/atpproject/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('posts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^wordcount/', include('wordcount.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

atpproject/posts/urls.py
from django.conf.urls import url
from . import views
# from django.views.generic import ListView, DetailView
#from posts.models import Posts

app_name = 'posts'

urlpatterns = [
    url(r'^posts/$', views.posts , name='posts'), # post slash nothing
    url(r'^$', views.index, name="index"),
    url(r'^details/(?P<pk>\d+)/$', views.details , name='details') # '\d+' > at least one or more digits
] 

atpproject/wordcount/urls.py
from django.conf.urls import url
from . import views

app_name = 'wordcount'

urlpatterns = [
    url(r'^$', views.count , name='count'), # post slash nothing
    # url(r'^details/(?P<id>\d+)/$', views.details , name='details') # '\d+' > at least one or more digits
    # url(r'^$', views.count , name='count'),
] 

atpproject/posts/models.py
from django.db import models
from datetime import datetime

# Create your models here.


class Posts(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    image = models.ImageField(upload_to="media", blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Posts'

atpproject/wordcount/models.py
from django.db import models

# Create your models here.

atpproject/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Posts  # import Models to show on Page
# Create your views here.


def index(request):
    # return HttpResponse('halo')
    posts = Posts.objects.all()

    # Pagination Code #######################

    paginator = Paginator(posts, 4)
    page = request.GET.get('page')

    try:
        items = paginator.page(page)
    except PageNotAnInteger as e:
        #print(e)
        items = paginator.page(1)
    except EmptyPage as ep:
        #print(ep)
        items = paginator.page(paginator.num_pages)
    
    index = items.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 5 if index >= 5 else 0
    end_index = index + 5 if index <= max_index - 5 else max_index
    page_range = paginator.page_range[start_index:end_index]

    # End of Pagination Code ################

    context = {
        'title': 'Latest Post',
        'posts': posts,
        'page_range' : page_range,
        'items' : items
    }


    return render(request, 'posts/index.html', context)

def posts(request):
    # return HttpResponse('halo')
    posts = Posts.objects.all()[:10]
    context = {
        'title': 'Post List',
        'posts': posts,
    }

    return render(request, 'posts/post-list.html', context)


def details(request, pk):
    # try:

    #     post = Posts.objects.get(id=id) # id that coming from urls
    #     context = {
    #         'post' : post
    #     }

    # except Posts.DoesNotExist:
    #     raise Http404("Post Does Not Exist")

    post = get_object_or_404(Posts, id=pk)  # shortcut
    context = {
        'post': post,
    }
    return render(request, 'posts/details.html', context)

atpproject/wordcount/views.py
from django.shortcuts import render
from django.http import HttpResponse
from collections import Counter

# Create your views here.
def count(request):
    context = {
        'title' : 'WordCount',
    }
    if request.method == "POST":
        print('*'*50)
        print(request.POST)
        print('*'*50)

        textToCount = request.POST.get('textbox')
        textcorpus = textToCount.split()
        countWord = Counter(textcorpus).most_common()
        counted = []
        for x in countWord:
            a = x[1] * 100. / len(textcorpus)
            b = list(x) # change tuple to list so the value can be changed
            b.insert(2, round(a, 2))
            counted.append(b)
        # counted = [(i, textcorpus.count(i) * 100. / len(textcorpus)) for i in set(textcorpus)]
        # counted = [x for x in countWord.most_common()]
        # kind = []
        # for x in counted:
        #     x = (str(x[1])*100/len(counted))            
        #     kind.append(x)
        # print(countWord.most_common())
        # print(counted) 
        
        return render(request, "wordcount/wordcount-result.html", {
            'text' : textToCount,
            'title' : 'WordCount',
            'items' : counted
        })

    return render(request, "wordcount/wordcount.html", context)

atpproject/posts/templates/posts/details.html
{% extends 'posts/layout.html' %}
{% block content %}
<h3 class="center-align red accent-1"> {{ post.title }} </h3>
<div class="card">
    <div class="card-content">
        {{ post.body }}
    </div>
    <div class="card-action">
        {{post.created_at}}
        {% comment %} <br>
        {{post.created_at|date:"Y-m-d"}} {% endcomment %}
        
    </div>
</div>
<a class="btn red lighten-1" href="{% url 'posts:index' %}"> Go Back</a>
{% endblock %}

atpproject/posts/templates/posts/index.html
{% extends 'posts/layout.html' %} {% block content %}


<h3 class="center-align red accent-1"> {{ title }} </h3>

{% for post in items%}
<!-- <li class="collection-item"> <a href="/posts/details/{{post.id}}"> {{post.title}}</a></li>  this is hardcoded url-->
<!-- <li class="collection-item"> <a href="{% url 'posts:details' post.id %} "> </a></li><br>  this is dinamic url -->
<div class="col s12 m7">
    <div class="card horizontal">
        <div class="card-image">
                {% if post.image %}
                <img src= '{{ post.image.url }}' width="240" >
                {% endif %}
        </div>
        <div class="card-stacked">
            <div class="card-content">
                <h4 class="header">
                    <a style="color: #ee6e72;" href="{% url 'posts:details' post.id %}">{{post.title}}</a>
                </h4>
                <p>{{ post.body|safe|truncatewords:"50"|linebreaks }}</p>
            </div>
            <div class="card-action">
                Posted on : {{post.created_at}}
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% include "posts/pagination.html" %}
 {% endblock %}

atpproject/posts/templates/posts/layout.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href='{% static "css/base.css" %}' >
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    
    <title>Advanced Pacific</title>
    <!-- Compiled and minified CSS -->
</head>

<header>
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo">ATP</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
           <ul id="nav-mobile" class="right hide-on-med-and-down">
               <li><a href="/">Home</a></li>
               <li><a href="/posts">Posts</a></li>
               <li><a href="/wordcount">WordCount</a></li>
               <li><a href="/admin">Admin Login</a></li>
           </ul>
           <ul class="side-nav" id="mobile-demo">
                <li><a href="/">Home</a></li>
                <li><a href="/posts">Posts</a></li>
                <li><a href="/admin">Admin Login</a></li>
          </ul>
        </div>
    </nav>
</header>

<main>
  <body>
   
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
   
<script src="https://code.jquery.com/jquery-2.1.2.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>

</body>
</main>


<footer class="page-footer">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text">Footer Content</h5>
          <p class="grey-text text-lighten-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae, ducimus. </p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Links</h5>
          <ul>
            <li><a class="grey-text text-lighten-3" href="#!">Link 1</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 2</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 3</a></li>
            <li><a class="grey-text text-lighten-3" href="#!">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2018 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
  </footer>
<script>
    $(".button-collapse").sideNav();
</script>
</html>

atpproject/posts/templates/posts/pagination.html
{% if items.has_other_pages %}
<div class="center-align">
  <ul class="pagination">
    {% if items.has_previous %}
    <li class="active">
      <a href="?page={{items.previous_page_number}} ">
        <i class="material-icons">chevron_left</i>
      </a>
    </li>
    {% else %}

    <li class="disabled">
      <a href="#!">
        <i class="material-icons">chevron_left</i>
      </a>
    </li>

    {% endif %}'
    {% for i in page_range %} 
      {% if items.number == i %}

        <li class="active">
          <a href="#!"> {{ i }} </a>
        </li>
        
      {% else %}
        <li class="waves-effect">
          <a href="?page={{ i }} ">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}
    {% if items.has_next %}
      {% comment %} <li class="waves-effect">
        <a href="?page={{items.paginator.num_pages}}"> Last
        </a>
      </li> {% endcomment %}
      <li class="active">
        <a href="?page={{items.next_page_number}}">
          <i class="material-icons">chevron_right</i>
        </a>
      </li>
    {% else %}

      <li class="disabled">
        <a href="#!"></a>
        <i class="material-icons">chevron_right</i>
      </li>

    {% endif %}
  </ul>
</div>
{% endif %}

atpproject/posts/templates/posts/post-list.html
{% extends "posts/layout.html" %}

{% block content %}
<h3 class="center-align red accent-1"> {{ title }} </h3>
<ul class="collection">
    {% for post in posts%}
    <!-- <li class="collection-item"> <a href="/posts/details/{{post.id}}"> {{post.title}}</a></li>  this is hardcoded url-->
    <li class="collection-item"> <a href="{% url 'posts:details' post.id %} "> {{ post.title }}</a></li><!--  this is dinamic url -->
    {% endfor %}
</ul>
{% endblock %}

atpproject/posts/templates/wordcount/wordcount-result.html
{% extends "posts/layout.html" %} {% block content %}
<h3 class="center-align red accent-1"> {{ title }} </h3>
<div class="card">
    <div class="card-content">
        {{ text }}
    </div>
    <h6 class="center-align red accent-1"> Counted Words </h6>
    <div class="card-action">
        {% for item, counter, percentage in items %}
        <mark> {{ item }} </mark> : {{ counter }} occurence , percentage : {{ percentage }} %
        <span></span>
        <br> {% endfor %}
        <style>
            mark {
                background-color: yellow;
                color: black;
            }
        </style>
    </div>
</div>
{% endblock content %}

atpproject/posts/templates/wordcount/wordcount.html
{% extends "posts/layout.html" %} {% block content %}

<h3 class="center-align red accent-1"> {{ title }} </h3>
<div class="container">
    <div class="row">
        <form class="col s12" action="/wordcount/" method="POST">
            {% csrf_token %}
            <div class="row">
                <div class="input-field col s12">
                    <textarea id="textarea1" name="textbox" class="materialize-textarea"></textarea>
                    <label for="textarea1">Input a Text to Count</label>
                    <button class="btn" type="submit">Submit</button>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock content %}